services:
  minio:
    restart: always
    image: minio/minio
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_volume:/var/lib/minio/data
    command:
      server /var/lib/minio/data --console-address ":9001"

volumes:
  minio_volume:
    driver: local