spring:
  application:
    name: spring-boot-cloud-storage
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  session:
    redis:
      namespace: spring:session
  data:
    redis:
      host: localhost
      port: 6379
      password: redisrootpassword
  minio:
    endpoint: http://localhost:9000
    access-key: CRykhwhftrDUgU55wvJR
    secret-key: ompxFEYjjhSUoz3AZ5QIQPB8VkvGL8wacuyxcyz2
    bucket: my-bucket