spring:
  application:
    name: spring-boot-cloud-storage
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  minio:
    endpoint: http://localhost:9000
    access-key: 9DoDjTvmIhbTCN5AMh8i
    secret-key: iVhZGLZbYhbqCsJQ10rBYmH2fvyw2hm4a8k2Kh7M
    bucket: my-bucket